### ISSUE TITLE
UI Customize

### ISSUE THREAD

**Issue by 0xARK** [AirenSoft/OvenPlayer#138]
Hello ! I'm sorry to bother you again for so little, I should have asked that in my last post. 

The player documentation tells us that we can change the color of the volume bar and the loader circle by providing us their classes : .ovp-volume-silder .ovp-volume-slider-value for the volume and .ovp-ellipsis div for the loader. 

However, I tried to change background color, line color, and many other elements but nothing worked :(

Can someone please help me?

Thank you for your help.

Mateo

**Comment by SangwonOh** [comment]
@0xARK Hi. We've changed css classes quite a lot. But document didn't updated. Thank you for your reporting.

New css class for UI elements is 

```css
/* progress bar */
.op-progressbar .op-play-background-color {
    background-color: red;
}

/* volume slider */
.op-volume-controller .op-volume-slider-container .op-volume-silder .op-volume-slider-value {
    background-color: red;
}

/* loader */
.op-spinner-container .op-spinner {
    border-top: 4px solid red;
}
```
Document will be updated soon. Thanks.
